### ISSUE TITLE
Build Collector layer on demond

### ISSUE THREAD

**Issue by wangzlei** [open-telemetry/opentelemetry-lambda#5]
**Is your feature request related to a problem? Please describe.**
Build Collector layer based on user's config, please see details in https://github.com/open-telemetry/opentelemetry-collector-builder/issues/4

**Describe the solution you'd like**
Use opentelemetry-collector-builder to build the Lambda collector extension in AWS Lambda layer

**Comment by vasireddy99** [comment]
Since the repo has been moved [here ](https://github.com/open-telemetry/opentelemetry-collector/tree/main/cmd/builder), Does this issue suggests to use these [commands](https://github.com/open-telemetry/opentelemetry-collector/tree/main/cmd/builder#opentelemetry-collector-builder) which allows users to build using the custom configurations.

**Comment by serkan-ozal** [comment]
@wangzlei @tylerbenson does this issue still relevant? And we already have this issue https://github.com/open-telemetry/opentelemetry-lambda/issues/100

**Comment by tylerbenson** [comment]
Definitely seems like a duplicate.  Closing.
