### ISSUE TITLE
Ability to set log-level of the collector

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-lambda#63]
OTel collector only accepts log-level as a command line flag. But since extensions are automatically started by lambda, there doesn't seem to be any way to change this. Being able to set log-level is important when debugging issues such as connectivity to backends, creds, etc. Perhaps we need to change the extension from the Go binary itself to a shell script which can have arguments passed via environment variable.

**Comment by anuraaga** [comment]
For debugging, I tried this sort of script

```
#!/bin/bash

echo "Starting collector"
/opt/collector --log-level debug
```

@wangzlei Just want to confirm again, what sort of problems do you see with a starter script approach? I think the only signal lambda sends is `SIGKILL` which should work the same whether it's the binary, or the binary started by bash.

**Comment by anuraaga** [comment]
By the way, that didn't actually enable logging. Now I found this which can probably enable debug logging :)

https://github.com/open-telemetry/opentelemetry-lambda/blob/main/collector/collector.go#L85

**Comment by rakyll** [comment]
We should also replace the existing logln with zap to honor the log format and the log levels.

**Comment by wangzlei** [comment]
@anuraaga Bootstrap process can be gracefully shutdown by [handling lambda SHUTDOWN event,](https://github.com/open-telemetry/opentelemetry-lambda/blob/main/collector/main.go#L80-L81) Lambda allows 500ms before destroying container. If using shell as bootstrap to indirectly launch a process, that process will be suddenly closed when container gets destroyed, there is no chance to flush the data in buffer.

Back to your question, it is ok to use shell to launch collector binary because we don't have batch processor in collector extension.
