### ISSUE TITLE
Proposal: Include Batch processor

### ISSUE THREAD

**Issue by pmm-sumo** [open-telemetry/opentelemetry-lambda#89]
**Is your feature request related to a problem? Please describe.**

Currently, [no processors are included](https://github.com/open-telemetry/opentelemetry-lambda/blob/main/collector/lambdacomponents/default.go#L45-L48) in the collector for Lambda. This makes it impossible to use Batch procesor. Missing it in the pipeline causes some issues, such as causing sending not-efficient batches by the exporter or not being able to limit maximum batch size

**Describe the solution you'd like**

Include Batch processor

**Comment by pmm-sumo** [comment]
cc @alolita @mrumian-sumo

**Comment by wangzlei** [comment]
Removing processors from Lambda collector extension because we want to make sure force_flush() is blocked until backend returns response to lambda function, the sequence diagram is: 
force_flush(Lambda runtime, user's Lambda function)  ->  collector receiver -> collector exporter -> backend service

Adding batching processor means it breaks to 2 flows, may get problem described in [design proposal](https://github.com/open-telemetry/opentelemetry-lambda/blob/main/docs/design_proposal.md#21-lambda-freeze)
 1. force_flush(Lambda runtime, user's Lambda function)  ->  collector receiver -> batchProcessor
    (Lambda Freeze)
 2.  batchProcessor -> collector exporter -> backend service


BatchProcessor improves efficiency most likely in collector mode but not in agent mode. In Lambda there is only one application, so alternatively we can batch/aggregate telemetry data from SDK side instead of Collector side.

**Comment by serkan-ozal** [comment]
@pmm-sumo in the latest version of the collector, `batch` processor is included and it is suggested to use by `decouple` processor (when batch processor is enabled, `decouple` processor is added right after it). 
https://github.com/open-telemetry/opentelemetry-lambda/blob/2087b126ae080573ba2944d2043245947b0e73a6/collector/lambdacomponents/default.go#L73

**Comment by serkan-ozal** [comment]
@tylerbenson do you think we can close this one?
