### ISSUE TITLE
Unknown exporters type - what types are supported?

### ISSUE THREAD

**Issue by deki** [open-telemetry/opentelemetry-lambda#99]
Hi,

I followed these steps https://github.com/open-telemetry/opentelemetry-lambda/blob/main/collector/README.md to publish the OpenTelemetry Collector Lambda layer from scratch.

However I noticed https://github.com/open-telemetry/opentelemetry-lambda/blob/main/collector/config.yaml is missing X-Ray so I defined a custom config (as described here: https://aws-otel.github.io/docs/getting-started/x-ray#configuring-the-aws-x-ray-exporter), looks similar to this https://github.com/aws-observability/aws-otel-lambda/blob/main/adot/collector/config.yaml in the end.

However it doesn't work:
```
info	service/application.go:277	Starting otelcol...	{"Version": "v0.1.0", "NumCPU": 2}
info	service/application.go:185	Setting up own telemetry...
info	service/application.go:220	Loading configuration...
Error: cannot load configuration: unknown exporters type "awsxray" for awsxray

```

If I switch from awsxray to jaeger, I get `Error: cannot load configuration: unknown exporters type "jaeger" for jaeger`. So I wonder what am I missing? What exporters are actually supported by the Lambda layer collector?

**Comment by wangzlei** [comment]
Right now Lambda collector extension supports limit number of collector component due to the reason in [design proposal 2.2 and 2.3](https://github.com/open-telemetry/opentelemetry-lambda/blob/main/docs/design_proposal.md#22-memory-consumption)

If you want XRay support please use AWS downstream repo https://github.com/aws-observability/aws-otel-lambda, it has ready-to-use Lambda layer, refer doc https://aws-otel.github.io/docs/getting-started/lambda

**Comment by wangzlei** [comment]
Create a requirement to build custom collector layer on demand
https://github.com/open-telemetry/opentelemetry-lambda/issues/100

**Comment by deki** [comment]
Thanks @wangzlei I noticed the ready-to-use layers, however I've created a sample for PHP (see https://github.com/brefphp/bref/issues/921), so the existing layers are not a good fit. #100 would definitely solve it, therefore closing this issue.
